---
title: News
date: last-modified
---

## quarto-svelte 2.0.0

- Rename Sverto to quarto-svelte
  - **Breaking:** `filters: ["sverto"]` is now `filters: ["quarto-svelte"]`
  - **Breaking:** `sverto.use` is now `quarto-svelte.use`
  - Repo name is now `jimjam-slam/quarto-svelte`, but `jimjam-slam/sverto` will continue to work
- Upgrade from Svelte 3 to Svelte 5
  - For notes on rewriting existing Svelte components for Svelte 5, see the [Svelte 5 Migration Guide](https://svelte.dev/docs/svelte/v5-migration-guide)
- Now uses web components
  - **Breaking:** in addition to general Svelte 5 migration, components for quarto-svelte need to have a [custom element option](https://svelte.dev/docs/svelte/custom-elements)
  - **Breaking:** old instantiation syntax no longer works in Svelte 5. Instead, use an HTML template or JavaScript to create an element with the custom element name

## Sverto 1.0.0

- Big refactor of sverto makes it easier to use and more compatible with Quarto's other features!
  - Use Sverto in a Quarto document by adding `sverto` to `filters` in the document frontmatter
  - Add Svelte files to a document using the frontmatter key `sverto.use`
  - No need for magic blocks anymore!
  - When working in a website project, optionally use the `sverto` project type to cut down on duplicate Svelte compilation Quarto documents
- Works properly with Quarto includes
- **Requires Quarto pre-release 1.5.25 or higher on Windows,** but should work fine on Quarto 1.4 on macOS and Linux.

## Sverto 0.0.3

- Migrated from [`360-info/sverto`](https://github.comn/360-info/sverto) to [`jimjam-slam/sverto`](htps://github.com/jimjam-slam/sverto). Old GitHub links are maintained.

## Sverto 0.0.2

- Bump minimum Quarto version to 1.3.0.
- Fixes for compatibility with newer Quarto 1.3 pre-releases
  - Quarto's switch from Pandoc 2 to Pandoc 3 caused some issues with the way Sverto identifies Svelte import statements. This should no longer be a problem.
- We now take advantage of the improved `.quartoignore` functionality in Quarto 1.3 to:
  1. avoid copying the `docs` folder in with the project template; and
  2. include the `.gitignore` with the template

## 0.0.1

- Initial release
